### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by binarydoubling** [stemkoski/three.py#12]
I cloned this repository and put it in my project. There are so many errors, some of which relate to how you try to handle input (it's not pygame.-key-, it's pygame.key.-key-). So I spent an hour and a half fixing these errors. Also, there are errors with the "*" operator when importing modules. You cannot all modules from a folder from a script that is in the same folder. What happens is the script imports itself.

So, these need to be fixed. I can definitely make a pull request with my fixes if you like.

P.S. HOW DID YOU GET ANYTHING TO WORK WITH THESE ERRORS!!

**Comment by stemkoski** [comment]
I'm sorry to hear that you're having some issues. Since nobody else seems to be having any of these issues, it would be helpful if you could be more specific. For example:

- what type of computer (PC/Mac, and which OS version) are you using? 
- what version of OpenGL is running on your computer?
- what version of Python and PyGame and PyOpenGL are you using?
- are you running programs from the command line or IDLE or something else?
- which of the Three.py programs are you running, and what are the specific error messages?

Regarding "pygame.key" for input, this isn't necessary. See, for example, https://pythonprogramming.net/pygame-tutorial-moving-images-key-input/. Maybe this was necessary for a previous version of Pygame; again, this is why it will be helpful for us to have more information about your issue. 

If you can be more specific with an example of an issue, please feel free to open a new issue with all the relevant information so that we can help you effectively.
